package com.oyetech.languageModule.keyset

/**
Created by Erdi Özbek
-20/04/2024-
-12:06-
 **/

object LanguageKeyyyyy {

    var PRIVACY_POLICY = ("PRIVACY_POLICY")
    var TERMS_AND_CONDITIONS = ("TERMS_AND_CONDITIONS")
    var CANCEL = ("CANCEL")
    var NO_INTERNET_CONNECTION = ("NO_INTERNET_CONNECTION")
    var CLOSE = ("CLOSE")
    var DELETE = ("DELETE")
    var SEND = ("SEND")
    var DEFAULT_ERROR = ("DEFAULT_ERROR")

    var RANDOM = ("RANDOM")
    var VIEWS = ("VIEWS")
    var TOPLIST = ("TOPLIST")
    var RELEVANCE = ("RELEVANCE")
    var DATE_ADDED = ("DATE_ADDED")
    var FAVORITES = ("FAVORITES")
    var ERROR_LIST_EMPTY = ("ERROR_LIST_EMPTY")

    var SETTINGS = ("SETTINGS")

    var SEARCH = ("SEARCH")
    var CATEGORY_LIST = ("CATEGORY_LIST")
    var FEEDBACK_ALREADY_SENT_DIALOG_DESC = ("FEEDBACK_ALREADY_SENT_DIALOG_DESC")
    var FEEDBACK_ALREADY_SENT_DIALOG_TITLE = ("FEEDBACK_ALREADY_SENT_DIALOG_TITLE")
    var FEEDBACK_ALREADY_SEND = ("FEEDBACK_ALREADY_SEND")
    var FEEDBACK_SEND_SUCCESS_MESSAGE = ("FEEDBACK_SEND_SUCCESS_MESSAGE")
    var FEEDBACK_EMAIL_HINT = ("FEEDBACK_EMAIL_HINT")
    var FEEDBACK_HEADER_HINT = ("FEEDBACK_HEADER_HINT")
    var FEEDBACK_BODY_HINT = ("FEEDBACK_BODY_HINT")
    var CONTACT_WITH_US = ("CONTACT_WITH_US")
    var DOWNLOAD_IMAGE_START = ("DOWNLOAD_IMAGE_START")
    var MORE_LIKE_THIS = ("MORE_LIKE_THIS")
    var FILE_SIZE = ("FILE_SIZE")
    var VIEW = ("VIEW")
    var WRITE_EXTERNAL_REQUIRED = ("WRITE_EXTERNAL_REQUIRED")
    var RATIO = ("RATIO")
    var AT_LEAST = ("AT_LEAST")
    var EXACTLY = ("EXACTLY")
    var SYSTEM_RESOLUTION = ("SYSTEM_RESOLUTION")
    var DESC = ("DESC")
    var ASC = ("ASC")
    var GENERAL = ("GENERAL")
    var PEOPLE = ("PEOPLE")
    var ANIME = ("ANIME")

    var SKETCHY = ("SKETCHY")
    var SFW = ("SFW")
    var NFSW = ("NFSW")
    var JPG = ("JPG")
    var PNG = ("PNG")

    var FEEDBACK_HEADER_ERROR = ("FEEDBACK_HEADER_ERROR")
    var FEEDBACK_BODY_ERROR = ("FEEDBACK_BODY_ERROR")
    var FEEDBACK_EMAIL_ERROR = ("FEEDBACK_EMAIL_ERROR")

    var PREMIUM_MEMBERSHIP_SHORT_DESC = ("PREMIUM_MEMBERSHIP_SHORT_DESC")
    var PREMIUM_MEMBERSHIP_HEADER = ("PREMIUM_MEMBERSHIP_HEADER")

    var SHARE_IMAGE = ("SHARE_IMAGE")
    var DOWNLOAD_IMAGE = ("DOWNLOAD_IMAGE")
    var DOWNLOAD_IMAGE_DESC = ("DOWNLOAD_IMAGE_DESC")

    var SUBSCRIPTION_END_DATE = ("SUBSCRIPTION_END_DATE")
    var YOU_ARE_A_PREMIUM_MEMBER = ("YOU_ARE_A_PREMIUM_MEMBER")

    var WEEKLY = ("WEEKLY")
    var MONTHLY = ("MONTHLY")
    var YEARLY = ("YEARLY")
    var AD_FREE_USE = ("AD_FREE_USE")

    var CAMERA_STORAGE_PERMISSION_INFO = ("CAMERA_STORAGE_PERMISSION_INFO")
    var CAMERA_STORAGE_PERMISSION = ("CAMERA_STORAGE_PERMISSION")
    var STORAGE_PERMISSION_INFO = ("STORAGE_PERMISSION_INFO")
    var CAMERA_PERMISSION_INFO = ("CAMERA_PERMISSION_INFO")
    var MICROPHONE_PERMISSION_INFO = ("MICROPHONE_PERMISSION_INFO")
    var MICROPHONE_PERMISSION = ("MICROPHONE_PERMISSION")

    var STORAGE_PERMISSION = ("STORAGE_PERMISSION")
    var CAMERA_PERMISSION = ("CAMERA_PERMISSION_FAILED")


}