apply plugin: 'com.android.library'
apply from: '../android_commons.gradle'

android {
    namespace 'com.oyetech.googlelogin'
}

dependencies {
    implementation project(Modules.domain)

    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.auth)

    implementation(libs.activity)
    implementation(libs.androidx.appcompat)
    implementation(libs.credentials)
    implementation(libs.credentials.play.services.auth)
    implementation(libs.googleid)
}
